name: '4-projects-plan'

on:
  pull_request:
    branches:
      - production
    paths:
      - '4-projects/**'
      - '.github/workflows/4-projects-*.yaml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  STAGE: '4-projects'
  TF_VERSION: '1.3.0'

jobs:
  plan-shared:
    name: 'Plan - Shared Projects'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account: ${{ secrets.TF_SA_PROJECTS }}
          access_token_lifetime: '3600s'
      - name: Terraform Init
        working-directory: 4-projects/business_unit_1/shared
        run: terraform init
      - name: Terraform Plan
        working-directory: 4-projects/business_unit_1/shared
        run: terraform plan -input=false -out=tfplan

  plan-development:
    name: 'Plan - Development Projects'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account: ${{ secrets.TF_SA_PROJECTS }}
          access_token_lifetime: '3600s'
      - name: Terraform Init
        working-directory: 4-projects/business_unit_1/development
        run: terraform init
      - name: Terraform Plan
        working-directory: 4-projects/business_unit_1/development
        run: terraform plan -input=false -out=tfplan

  plan-nonproduction:
    name: 'Plan - Non-Production Projects'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account: ${{ secrets.TF_SA_PROJECTS }}
          access_token_lifetime: '3600s'
      - name: Terraform Init
        working-directory: 4-projects/business_unit_1/nonproduction
        run: terraform init
      - name: Terraform Plan
        working-directory: 4-projects/business_unit_1/nonproduction
        run: terraform plan -input=false -out=tfplan

  plan-production:
    name: 'Plan - Production Projects'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account: ${{ secrets.TF_SA_PROJECTS }}
          access_token_lifetime: '3600s'
      - name: Terraform Init
        working-directory: 4-projects/business_unit_1/production
        run: terraform init
      - name: Terraform Plan
        working-directory: 4-projects/business_unit_1/production
        run: terraform plan -input=false -out=tfplan
